### ISSUE TITLE
Download issue.

### ISSUE THREAD

**Issue by Wildman48** [purutu/ACT.DFAssist#15]
Just a quick comment. I've always kept up to date with this plugin and thank you for that. But to let you know through windows 10 it thinks this is a virus and had trouble downloading it through ,chrome, firefox or windows. The work around was to disable all windows 10 antivirus to get it to download. Thought you should know sense I never had an issue before with your plugin.

**Comment by purutu** [comment]
Thank you for your comment.
Windows security always alert unsigned application. (EXE and DLL)
And this application doesn't signed. Because it is Unlicense License!

![image](https://user-images.githubusercontent.com/47320226/97048834-a8315000-15b5-11eb-8b6e-9d7622c9af04.png)
You can bypass this problem by check Unblock in property menu on any downloaded files. :)

Have a goodday!
